DELIMITER $$

CREATE EVENT Bulk_Completed
    ON SCHEDULE EVERY 2 HOUR STARTS '2016-09-23 09:00:00'
    DO BEGIN

INSERT IGNORE INTO PAMSGUI.BULK_PROCESSING_COMPLETED SELECT * FROM PAMSGUI.BULK_PROCESSING WHERE STATUS = 'COMPLETED'; 

DELETE FROM PAMSGUI.BULK_PROCESSING WHERE STATUS = 'COMPLETED';

END $$

DELIMITER ;

SET GLOBAL event_scheduler = ON;